apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-moving-averages
  namespace: sandbox
spec:
  schedule: "30 9 * * 2-6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: update-moving-averages
              image: qroksera.com/sandbox/update-moving-averages:202403060652
              env:
                - name: DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgre
                      key: username
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgre
                      key: password
                - name: DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: postgre
                      key: dbname
                - name: DATABASE_HOST
                  valueFrom:
                    secretKeyRef:
                      name: postgre
                      key: host
                - name: DATABASE_PORT
                  valueFrom:
                    secretKeyRef:
                      name: postgre
                      key: port
                - name: SLACK_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: slack-secret
                      key: token
                - name: SLACK_CHANNEL_ID
                  valueFrom:
                    secretKeyRef:
                      name: slack-secret
                      key: channel
          restartPolicy: OnFailure
