apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-moving-averages
  namespace: sandbox
spec:
  schedule: "30 8 * * 2-6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: update-moving-averages
              image: update-moving-averages:latest
              env:
                - name: DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgre
                      key: username
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgre
                      key: password
                - name: DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: postgre
                      key: dbname
                - name: DATABASE_HOST
                  valueFrom:
                    secretKeyRef:
                      name: postgre
                      key: host
                - name: DATABASE_PORT
                  valueFrom:
                    secretKeyRef:
                      name: postgre
                      key: port
          restartPolicy: OnFailure
